# Generated by Django 5.0.2 on 2024-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='payment',
            field=models.TextField(null=True),
        ),
    ]
