# Generated by Django 5.0.2 on 2024-03-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='guests',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
