# Generated by Django 5.0.2 on 2024-03-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0004_procedures_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guest',
            new_name='guests',
        ),
    ]
