# Generated by Django 5.0.2 on 2024-04-04 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0006_remove_procedures_days_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedures',
            name='size_cc',
        ),
    ]
